<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-24E6EFHK" failures="2" tests="12" name="com.myframework.testcases.homepage.VerifyHomeScreen" time="1.179" errors="0" timestamp="2024-02-19T22:44:35 IST" skipped="4">
  <testcase classname="com.myframework.testcases.homepage.VerifyHomeScreen" name="verifyHomePageTitle" time="0.028"/>
  <system-out/>
  <testcase classname="com.myframework.testcases.homepage.VerifyHomeScreen" name="verifyHomePageTitle" time="0.031"/>
  <system-out/>
  <testcase classname="com.myframework.testcases.homepage.VerifyHomeScreen" name="verifySignInBtnIsVisible" time="0.082"/>
  <system-out/>
  <testcase classname="com.myframework.testcases.homepage.VerifyHomeScreen" name="verifySignInBtnIsVisible" time="0.156"/>
  <system-out/>
  <testcase classname="com.myframework.testcases.homepage.VerifyHomeScreen" name="verifyMainMenuOptions" time="0.168"/>
  <system-out/>
  <testcase classname="com.myframework.testcases.homepage.VerifyHomeScreen" name="verifyMainMenuOptions" time="0.698"/>
  <system-out/>
  <testcase classname="com.myframework.testcases.homepage.VerifyHomeScreen" name="failedTestCase" time="0.002">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.myframework.testcases.homepage.VerifyHomeScreen.failedTestCase(VerifyHomeScreen.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- failedTestCase -->
  <system-out/>
  <testcase classname="com.myframework.testcases.homepage.VerifyHomeScreen" name="failedTestCase" time="0.008">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at com.myframework.testcases.homepage.VerifyHomeScreen.failedTestCase(VerifyHomeScreen.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- failedTestCase -->
  <system-out/>
  <testcase classname="com.myframework.testcases.homepage.VerifyHomeScreen" name="skippedTestCase" time="0.004">
    <skipped/>
  </testcase> <!-- skippedTestCase -->
  <system-out/>
  <testcase classname="com.myframework.testcases.homepage.VerifyHomeScreen" name="skippedTestCase" time="0.002">
    <skipped/>
  </testcase> <!-- skippedTestCase -->
  <system-out/>
  <testcase classname="com.myframework.testcases.homepage.VerifyHomeScreen" name="skippedTestCase2">
    <skipped/>
  </testcase> <!-- skippedTestCase2 -->
  <system-out/>
  <testcase classname="com.myframework.testcases.homepage.VerifyHomeScreen" name="skippedTestCase2">
    <skipped/>
  </testcase> <!-- skippedTestCase2 -->
  <system-out/>
</testsuite> <!-- com.myframework.testcases.homepage.VerifyHomeScreen -->
